package com.minimarket.web_minimarket.entity;

import jakarta.persistence.*;

import java.math.BigDecimal;

// Java Persistence API
@Entity // Marks the Product class as a JPA entity, meaning it represents a table in the database
@Table(name = "products") // Specifies the database table that the Product entity maps to. Here, it’s explicitly set to a table named products
public class Product {
    @Id // Marks the productId field as the primary key of the Product entity
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the productId field’s value is automatically generated by the database, using the IDENTITY strategy
    @Column(name = "product_id")
    private int productId;

    @Column(name = "product_name")
    private String productName;
    @Column(name = "product_price")
    private BigDecimal productPrice;
    @Column(name = "product_quantity")
    private int productQuantity;

    @ManyToOne // Defines a many-to-one relationship between the Product entity and the Category entity
    @JoinColumn(name = "category_id") // Specifies the foreign key column in the products table that links to the Category table
    private Category category;

    @ManyToOne
    @JoinColumn(name = "supplier_id")
    private Supplier supplier;

    // Constructors
    public Product() {}

    public Product(String productName, BigDecimal productPrice, int productQuantity, Category category, int productId, Supplier supplier) {
        this.productName = productName;
        this.productPrice = productPrice;
        this.productQuantity = productQuantity;
        this.category = category;
        this.productId = productId;
        this.supplier = supplier;
    }

    public Product(String productName, BigDecimal productPrice, int productQuantity, Category category, Supplier supplier) {
        this.productName = productName;
        this.productPrice = productPrice;
        this.productQuantity = productQuantity;
        this.category = category;
        this.supplier = supplier;
    }

    // Getters and setters
    public int getProductId() {
        return productId;
    }

    public void setProductId(int productId) {
        this.productId = productId;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public int getProductQuantity() {
        return productQuantity;
    }

    public void setProductQuantity(int productQuantity) {
        this.productQuantity = productQuantity;
    }

    public BigDecimal getProductPrice() {
        return productPrice;
    }

    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public Supplier getSupplier() {
        return supplier;
    }

    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }


    @Override
    public String toString() {
        return "Product{" +
                "productId=" + productId +
                ", productName='" + productName + '\'' +
                ", productPrice=" + productPrice +
                ", productQuantity=" + productQuantity +
                ", \n\tsupplier=" + supplier +
                ", \n\tcategory=" + category +
                "}";
    }
}
